name: Validate Docker Compose on Dev

on:
  push:
    branches:
      - dev

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 3: Debug - Check working directory
      - name: List project files
        run: ls -R .

      # Step 4: Run Docker Compose (up)
      - name: Start Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      # Step 5: Wait for services to start
      - name: Wait for services to start
        run: sleep 20

      # Step 6: Debug container logs if frontend fails
      - name: Check container status
        run: docker ps -a

      - name: Logs of frontend service
        if: always()  # Ensure this runs even if a previous step fails
        run: docker-compose logs frontend

      # Step 7: Verify services
      - name: Verify Database Service (db)
        run: docker-compose exec db echo "Database service is running"

      - name: Verify Adminer Service
        run: docker-compose exec adminer echo "Adminer service is running"

      - name: Verify Backend Service
        run: docker-compose exec backend echo "Backend service is running"

      - name: Verify Frontend Service
        run: docker-compose exec frontend echo "Frontend service is running"

      # Step 8: Clean up services
      - name: Clean up services
        run: docker-compose down --volumes
